
- name: Create a jenkins job using basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{item}}"
    url: http://172.31.88.15:8080
    user: admin
    password: "{{jenkins_password}}"
  loop: "{{ folders }}"


- name: create pipeline jobs
  ansible.builtin.include_tasks: mbranch-pipeline.yml
  loop: "{{ ci_pipeline_jobs }}"

- name: create single branch pipeline jobs
  ansible.builtin.include_tasks: sbranch-pipeline.yml
  loop: "{{ sbranch_pipeline_jobs }}"