- name: create config file
  ansible.builtin.template:
    src: m-job.xml
    dest: /tmp/m-job.xml
  vars:
    unique_key: lookup('community.general.random_string', special=false, upper=fasle, length=12)



- name: Create a jenkins job using basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/m-job.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    password: "{{jenkins_password}}"
    url: http://172.31.88.15:8080
    user: admin


