- name: if job exist or not
  community.general.jenkins_job_info:
    name: "{{item.dir}}/{{item.name}}"
    password: "{{jenkins_password}}"
    url: http://172.31.88.15:8080
    user: admin
  register: out
  ignore_errors: yes


- name: create config file
  ansible.builtin.template:
    src: job.xml
    dest: /tmp/job.xml
  when: out.failed | bool



- name: Create a jenkins job using basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/job.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    password: "{{jenkins_password}}"
    url: http://172.31.88.15:8080
    user: admin
  when: out.failed | bool


